In [123]:
# Import NumPy and print its version
import numpy as np
np_version = np.__version__
print('NumPy version:', np_version)

NumPy version: 2.0.2


In [124]:
# Create a Python list and print each item
my_list = [1, 2, 3, 4, 5]
for item in my_list:
    print(item)

1
2
3
4
5


In [125]:
# Convert the Python list to a NumPy array and print it
arr = np.array(my_list)
print('arr =', arr)

arr = [1 2 3 4 5]


In [126]:
# Create an array from 0 to 10 using arange and print it
arr_range = np.arange(0, 11)
print('arr_range =', arr_range)

arr_range = [ 0  1  2  3  4  5  6  7  8  9 10]


In [127]:
# Create an array from 0 to 10 with step 2 and print it
arr_step2 = np.arange(0, 11, 2)
print('arr_step2 =', arr_step2)

arr_step2 = [ 0  2  4  6  8 10]


In [128]:
# Create a 1D array of zeros (length 3) and print it
zeros_3 = np.zeros(3)
print('zeros_3 =', zeros_3)

zeros_3 = [0. 0. 0.]


In [129]:
# Create a 3x3 array of zeros and print it
zeros_3x3 = np.zeros((3,3))
print('zeros_3x3 =\n', zeros_3x3)

zeros_3x3 =
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [130]:
# Create a 1D array of ones (length 3) and print it
ones_3 = np.ones(3)
print('ones_3 =', ones_3)

ones_3 = [1. 1. 1.]


In [131]:
# Create a 3x3x3 array of ones and print its shape
ones_3x3x3 = np.ones((3,3,3))
print('ones_3x3x3 shape =', ones_3x3x3.shape)

ones_3x3x3 shape = (3, 3, 3)


In [132]:
# Create 10 evenly spaced values between 0 and 5 and print them
linspace_0_5 = np.linspace(0,5,10)
print('linspace_0_5 =', linspace_0_5)

linspace_0_5 = [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [133]:
# Generate 5 random numbers from uniform[0,1) and print
rand5 = np.random.rand(5)
print('rand5 =', rand5)

rand5 = [0.24244442 0.08389783 0.68615187 0.90312864 0.81494402]


In [134]:
# Generate a 2x3 array of random floats and print
rand_2x3 = np.random.rand(2,3)
print('rand_2x3 =\n', rand_2x3)

rand_2x3 =
 [[0.46826168 0.4666425  0.27989968]
 [0.08344969 0.41663342 0.95335178]]


In [135]:
# Generate 5 samples from the standard normal distribution and print
randn5 = np.random.randn(5)
print('randn5 =', randn5)

randn5 = [ 1.05380092  1.27553138 -0.82770074  0.70867927  0.85114638]


In [136]:
# Generate a 2x2 array of random floats and print
rand_2x2 = np.random.rand(2,2)
print('rand_2x2 =\n', rand_2x2)

rand_2x2 =
 [[0.32814471 0.61793553]
 [0.75255042 0.49389659]]


In [137]:
# Generate a random integer in [0, 100) and print it
rand_int = np.random.randint(100)
print('rand_int =', rand_int)

rand_int = 34


In [138]:
# Generate 10 random integers between 1 and 99 and print them
rand_ints_1_100 = np.random.randint(1, 100, 10)
print('rand_ints_1_100 =', rand_ints_1_100)

rand_ints_1_100 = [46 50 70 66 53 15 39 70 66 40]


In [139]:
# Create a 1D array and reshape it to 3x3; store and print both
arr = np.array([1, 2, 3, 4, 5, 4, 6, 7, 8])
arr_reshaped = arr.reshape(3,3)
print('arr =', arr)
print('arr_reshaped =\n', arr_reshaped)

arr = [1 2 3 4 5 4 6 7 8]
arr_reshaped =
 [[1 2 3]
 [4 5 4]
 [6 7 8]]


In [140]:
# Print the maximum value in the array 'arr'
arr_max = arr.max()
print('arr_max =', arr_max)

arr_max = 8


In [141]:
# Print the minimum value in the array 'arr'
arr_min = arr.min()
print('arr_min =', arr_min)

arr_min = 1


In [142]:
# Index of the maximum value in 'arr' and print it
arr_argmax = arr.argmax()
print('arr_argmax =', arr_argmax)

arr_argmax = 8


In [143]:
# Index of the minimum value in 'arr' and print it
arr_argmin = arr.argmin()
print('arr_argmin =', arr_argmin)

arr_argmin = 0


In [144]:
# Print the shape of 'arr'
arr_shape = arr.shape
print('arr_shape =', arr_shape)

arr_shape = (9,)


In [145]:
# Print the data type of the elements in 'arr'
arr_dtype = arr.dtype
print('arr_dtype =', arr_dtype)

arr_dtype = int64


In [146]:
# Create an array 'a' from 1 to 10 and print it
a = np.arange(1, 11)
print('a =', a)

a = [ 1  2  3  4  5  6  7  8  9 10]


In [147]:
# Access and print the element at index 8 from array 'a'
a_index_8 = a[8]
print('a_index_8 =', a_index_8)

a_index_8 = 9


In [148]:
# Slice the array 'a' from index 1 to 4 and print the result
a_slice_1_5 = a[1:5]
print('a_slice_1_5 =', a_slice_1_5)

a_slice_1_5 = [2 3 4 5]


In [149]:
# Slice the array 'a' from start to index 5 (exclusive) and print
a_slice_start_6 = a[:6]
print('a_slice_start_6 =', a_slice_start_6)

a_slice_start_6 = [1 2 3 4 5 6]


In [150]:
# Create a slice from 'a', assign to 'slice_a' and print it
slice_a = a[1:6]
print('slice_a =', slice_a)

slice_a = [2 3 4 5 6]


In [151]:
# Create a deep copy of 'slice_a' (so modifications won't affect original) and print it
copy = slice_a.copy()
print('copy =', copy)

copy = [2 3 4 5 6]


In [152]:
# Create a 3x3 2D NumPy array and print it
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('arr_2d =\n', arr_2d)

arr_2d =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [153]:
# Access and print the first row of the 2D array 'arr_2d'
arr_2d_row0 = arr_2d[0]
print('arr_2d_row0 =', arr_2d_row0)

arr_2d_row0 = [1 2 3]


In [154]:
# Access and print the element in first row, second column of 'arr_2d'
arr_2d_0_1 = arr_2d[0][1]
print('arr_2d_0_1 =', arr_2d_0_1)

arr_2d_0_1 = 2


In [155]:
# Access element using comma indexing (first row, second column) and print
arr_2d_0_1_comma = arr_2d[0,1]
print('arr_2d_0_1_comma =', arr_2d_0_1_comma)

arr_2d_0_1_comma = 2


In [156]:
# Slice the 2D array to get bottom-right 2x2 block and print
arr_2d_bottom_right = arr_2d[2:,1:]
print('arr_2d_bottom_right =\n', arr_2d_bottom_right)

arr_2d_bottom_right =
 [[8 9]]


In [157]:
# Get the first two rows of 'arr_2d' and print
arr_2d_first2 = arr_2d[:2]
print('arr_2d_first2 =\n', arr_2d_first2)

arr_2d_first2 =
 [[1 2 3]
 [4 5 6]]


In [158]:
# Create a boolean mask where elements of 'a' are greater than 5 and print it
bool_mask = a > 5
print('bool_mask =', bool_mask)

bool_mask = [False False False False False  True  True  True  True  True]


In [159]:
# Use the boolean mask to filter elements of 'a' and print the result
filtered_a_using_mask = a[bool_mask]
print('filtered_a_using_mask =', filtered_a_using_mask)

filtered_a_using_mask = [ 6  7  8  9 10]


In [160]:
# Directly filter 'a' for values greater than 5 and print
filtered_a_gt5 = a[a > 5]
print('filtered_a_gt5 =', filtered_a_gt5)

filtered_a_gt5 = [ 6  7  8  9 10]


In [161]:
# Print the array 'a' to show it is unchanged by previous slicing/filtering
a_copy_for_print = a
print('a =', a_copy_for_print)

a = [ 1  2  3  4  5  6  7  8  9 10]


In [162]:
# Demonstrate element-wise addition of 'a' with itself and print the result
a_add_a = a + a
print('a_add_a =', a_add_a)

a_add_a = [ 2  4  6  8 10 12 14 16 18 20]


In [163]:
# Demonstrate element-wise subtraction of 'a' from itself (should be zeros) and print
a_sub_a = a - a
print('a_sub_a =', a_sub_a)

a_sub_a = [0 0 0 0 0 0 0 0 0 0]


In [164]:
# Demonstrate element-wise multiplication of 'a' with itself and print
a_mul_a = a * a
print('a_mul_a =', a_mul_a)

a_mul_a = [  1   4   9  16  25  36  49  64  81 100]


In [165]:
# Show a handled divide-by-zero example so the notebook doesn't stop on error
try:
    result_div_zero = 1 / 0  # intentional error
except Exception as exc:
    result_div_zero = None
    print('Caught exception (as expected):', type(exc).__name__, '-', exc)
print('result_div_zero =', result_div_zero)

Caught exception (as expected): ZeroDivisionError - division by zero
result_div_zero = None


In [166]:
# Square each element in 'a' and print the result
a_squared = a ** 2
print('a_squared =', a_squared)

a_squared = [  1   4   9  16  25  36  49  64  81 100]


In [167]:
# Compute the square root of each element in 'a' and print
sqrt_a = np.sqrt(a)
print('sqrt_a =', sqrt_a)

sqrt_a = [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]


In [168]:
# Compute the exponential of each element in 'a' and print
exp_a = np.exp(a)
print('exp_a =', exp_a)

exp_a = [2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]


In [169]:
# Compute the maximum of 'a' using NumPy and print
np_max_a = np.max(a)
print('np_max_a =', np_max_a)

np_max_a = 10


In [170]:
# Compute the minimum of 'a' using NumPy and print
np_min_a = np.min(a)
print('np_min_a =', np_min_a)

np_min_a = 1


In [171]:
# Compute the sine of each element in 'a' and print
sin_a = np.sin(a)
print('sin_a =', sin_a)

sin_a = [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111]


In [172]:
# Compute the cosine of each element in 'a' and print
cos_a = np.cos(a)
print('cos_a =', cos_a)

cos_a = [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026 -0.83907153]
